version: "3.8"

services:
  emqx:
    image: emqx/emqx:5.5
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      EMQX_ALLOW_ANONYMOUS: "true"

  spring-boot:
    build: .
    container_name: lab307-app
    ports:
      - "8080:8080"
    depends_on:
      - emqx
